add Job object

diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -12,10 +12,12 @@ parse() {
   echo "Initializing common params..."
 
   case $resource_type in
-    deployment|d)
+    deployment|dp)
         # get image name
         image=$(jq -r .params.image_name < "$payload")
         tag=$(jq -r '.params.image_tag // "1.0"' < "$payload")
+        image_pull_policy=$(jq -r '.params.image_pull_policy // "IfNotPresent"' < "$payload")
+        restart_policy=$(jq -r '.params.restart_policy // "Always"' < "$payload")
         resource_request_memory=$(jq -r '.params.resource_request_memory // "512Mi"' < "$payload")
         resource_limit_memory=$(jq -r '.params.resource_limit_memory // "1Gi"' < "$payload")
         resource_request_cpu=$(jq -r '.params.resource_request_cpu // "500m"' < "$payload")
@@ -36,11 +38,23 @@ parse() {
         port_values=$(jq -r ".params.port_values[]? | if .name and .containerPort then (\"$(printf "%8s")\"+\"- name: \"+.name + \"\n$(printf "%10s")containerPort: \" + .containerPort) else empty end "  < $payload)
         replica=$(jq -r '.params.replica // "1"' < "$payload")
     ;;
-    service|s|svc)
+    job|jb)
+        # get image name
+        image=$(jq -r .params.image_name < "$payload")
+        tag=$(jq -r '.params.image_tag // "1.0"' < "$payload")
+        image_pull_policy=$(jq -r '.params.image_pull_policy // "IfNotPresent"' < "$payload")
+        restart_policy=$(jq -r '.params.restart_policy // "Always"' < "$payload")
+        env_values=$(jq -r ".params.env_values[]? | if .name and .value then (\"$(printf "%8s")\"+\"- name: \"+.name + \"\n$(printf "%10s")value: \\\"\" + .value + \"\\\"\") else empty end "  < $payload)
+        command=$(jq -r 'if .params.command then {command: .params.command} else empty end' < "$payload")
+        if [[ -n $command ]]; then
+          command=$( echo $command | j2y | awk '{print "        " $0}' )
+        fi
+    ;;
+    service|sv)
         port_values=$(jq -r ".params.port_values[]? | if .name and .port then (\"$(printf "%2s")\"+\"- name: \"+.name + \"\n$(printf "%4s")port: \"  + .port) else empty end "  < $payload)
         expose_type=$(jq -r '.params.expose_type // "ClusterIP"' < "$payload")
     ;;
-    configmap|cm|config|secret)
+    configmap|cm|secret|se)
         config_data=$(jq -r '.params.config_data // ""' < "$payload")
         if [[ -n $config_data ]]; then
           config_data=$( echo $config_data | j2y | awk '{print "  " $0}' )
@@ -60,23 +74,23 @@ validate() {
   echo "Validating params of \"$resource_type\" object..."
 
   case $resource_type in
-    deployment|d)
-      if [[ -z "$image" ]]; then
-       echo "Missing container image"
-       exit 1
-      fi
+    deployment|dp|job|jb)
+       if [[ -z "$image" ]]; then
+        echo "Missing container image"
+        exit 1
+       fi
     ;;
-    service|s|svc)
-      if [[ -z "$port_values" ]]; then
-       echo "Missing expose port values"
-       exit 1
-      fi
+    service|sv)
+       if [[ -z "$port_values" ]]; then
+        echo "Missing expose port values"
+        exit 1
+       fi
     ;;
-    configmap|cm|config|secret)
-      if [[ -z "$config_data" ]]; then
-       echo "Missing config data"
-       exit 1
-      fi
+    configmap|cm|secret|se)
+       if [[ -z "$config_data" ]]; then
+        echo "Missing config data"
+        exit 1
+       fi
     ;;
     *)
     ;;
@@ -90,33 +104,37 @@ apply() {
   echo "Applying changes of \"$resource_type\"..."
 
   case $resource_type in
-    deployment|d)
-      template="$(cat /opt/resource/templates/Deployment.yml)"
-      #eval "echo \"${template}\"" | sed '/^$/d'
-      eval "echo \"${template}\"" | sed '/^$/d' | kubectl apply -f -
-      result="$(jq -n "{version:{container:\"$image:$tag\", ref:$(kubectl get deploy/${resource_name} -n ${namespace} -o json | jq .metadata.resourceVersion)}}")"
-      echo "Deployment object successfully initialized"
+    deployment|dp)
+       template="$(cat /opt/resource/templates/Deployment.yml)"
+       #eval "echo \"${template}\"" | sed '/^$/d'
+       eval "echo \"${template}\"" | sed '/^$/d' | kubectl apply -f -
+       result="$(jq -n "{version:{container:\"$image:$tag\", ref:$(kubectl get deploy/${resource_name} -n ${namespace} -o json | jq .metadata.resourceVersion)}}")"
+       echo "Deployment object successfully initialized"
     ;;
-    service|s|svc)
-      template="$(cat /opt/resource/templates/Service.yml)"
-      eval "echo \"${template}\"" | sed '/^$/d' | kubectl apply -f -
-      #result="$(jq -n "{service:{selector:\"$resource_name\"}}")"
-      result="$(jq -n "{version:{ref:$(kubectl get svc/${resource_name} -n ${namespace} -o json | jq .metadata.resourceVersion)}, buildId: \"$BUILD_ID\"}")"
-      echo "Service object successfully initialized"
+    job|jb)
+       template="$(cat /opt/resource/templates/Job.yml)"
+       #eval "echo \"${template}\"" | sed '/^$/d'
+       eval "echo \"${template}\"" | sed '/^$/d' | kubectl apply -f -
+       result="$(jq -n "{version:{container:\"$image:$tag\", ref:$(kubectl get job/${resource_name} -n ${namespace} -o json | jq .metadata.resourceVersion)}}")"
+       echo "Job object successfully initialized"
     ;;
-    configmap|cm|config)
-      template="$(cat /opt/resource/templates/ConfigMap.yml)"
-      #eval "echo \"${template}\""
-      eval "echo \"${template}\"" | sed '/^$/d' | kubectl apply -f -
-      #result="$(jq -n "{version:{container:\"$image:$tag\"}}")"
-      result="$(jq -n "{version:{ref:$(kubectl get cm/${resource_name} -n ${namespace} -o json | jq .metadata.resourceVersion), buildId: \"$BUILD_ID\"}}")"
-      echo "ConfigMap object successfully created"
+    service|sv)
+       template="$(cat /opt/resource/templates/Service.yml)"
+       eval "echo \"${template}\"" | sed '/^$/d' | kubectl apply -f -
+       result="$(jq -n "{version:{ref:$(kubectl get svc/${resource_name} -n ${namespace} -o json | jq .metadata.resourceVersion)}, buildId: \"$BUILD_ID\"}")"
+       echo "Service object successfully initialized"
     ;;
-    secret)
-      template="$(cat /opt/resource/templates/Secret.yml)"
-      eval "echo \"${template}\"" | sed '/^$/d' | kubectl apply -f -
-      result="$(jq -n "{version:{ref:$(kubectl get secret/${resource_name} -n ${namespace} -o json | jq .metadata.resourceVersion), buildId: \"$BUILD_ID\"}}")"
-      echo "Secret object successfully created"
+    configmap|cm)
+       template="$(cat /opt/resource/templates/ConfigMap.yml)"
+       eval "echo \"${template}\"" | sed '/^$/d' | kubectl apply -f -
+       result="$(jq -n "{version:{ref:$(kubectl get cm/${resource_name} -n ${namespace} -o json | jq .metadata.resourceVersion), buildId: \"$BUILD_ID\"}}")"
+       echo "ConfigMap object successfully created"
+    ;;
+    secret|se)
+       template="$(cat /opt/resource/templates/Secret.yml)"
+       eval "echo \"${template}\"" | sed '/^$/d' | kubectl apply -f -
+       result="$(jq -n "{version:{ref:$(kubectl get secret/${resource_name} -n ${namespace} -o json | jq .metadata.resourceVersion), buildId: \"$BUILD_ID\"}}")"
+       echo "Secret object successfully created"
     ;;
     *)
     ;;
